name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # roda 1x por dia (meia-noite UTC)
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: Platane/snk@v3
        with:
          github_user_name: felix3224
          outputs: |
            dist/pacman-contribution-graph.svg?palette=github-dark
            dist/pacman-contribution-graph-dark.svg?palette=github-light

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
